"""Rename assignee to assignee_id in Task model

Revision ID: 060603075cb6
Revises: 776b8bfff177
Create Date: 2024-06-05 12:19:32.500435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '060603075cb6'
down_revision = '776b8bfff177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=False))
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###
