"""Fixed backref names to avoid conflicts

Revision ID: 776b8bfff177
Revises: 72299a36ba72
Create Date: 2024-06-04 22:42:26.956734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '776b8bfff177'
down_revision = '72299a36ba72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', sa.Integer(), nullable=False))
        batch_op.alter_column('project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint('task_ibfk_3', type_='foreignkey')
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('task_ibfk_3', 'user', ['assignee_id'], ['id'])
        batch_op.alter_column('project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###
