"""Update relationships between User and Task models

Revision ID: 95a9d5a20c55
Revises: d7343937d7d8
Create Date: 2024-06-05 13:21:18.658763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95a9d5a20c55'
down_revision = 'd7343937d7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['assignee_id'], ['id'])
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###
