"""Updated Task model relationships

Revision ID: d7343937d7d8
Revises: 060603075cb6
Create Date: 2024-06-05 12:44:48.252217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7343937d7d8'
down_revision = '060603075cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', sa.Integer(), nullable=False))
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###
